'''You only need to edit this file to complete your mission!'''

import random
import datetime
now = datetime.datetime.now()

def bytes_to_string(packet_bytes: bytes):
	field_strings = [packet_bytes[i:i+4][::-1].hex()  for i in range(0, len(packet_bytes), 4)]
	return ':'.join(field_strings)

def string_to_bytes(packet_string: str):
	field_bytes = [bytes.fromhex(field)[::-1] for field in packet_string.split(':')]
	return b''.join(field_bytes)

def create_packet(key):
	string_to_send = ''
	''' Use this function to generate new packets from the client. (sudo required) '''

	# Your Mission for Weapons Role #

	### Send a packet to turn the shields on ###
	if key=='space':
		string_to_send = "deadbeef:00000020:00000002:00000000:0000000c:4c821d3c:00000004:00000000" #edit this, warning dont use ctrl-C on the terminal

	### Send a packet to load both tubes ###

	### Create a hotkey to load each of the ordinance types ###
	if key=='0':
		string_to_send = ""
  
	if key=='9':
		string_to_send = ""
		
		
	# Your Mission for Helm Role #

	### Send a packet to adjust the pitch (diving/neutral/climbing) ###

	### Send a packet to turn the ship hard right ###2

	### Create a hotkey for each increment of 10 on the impulse slider (yellow vertical) ###

	# What can you do for other roles? #
	
	print(f"Sending Packet... {string_to_send}", end='\r')

	return string_to_bytes(string_to_send), False

def forward_packet(client_packet: bytes):
	''' Use this function to manipulate packets generated by the client (x). '''

	### Filter out the reoccuring packet - what could this be used for? ###
	if bytes_to_string(client_packet) == 'reoccuring packet':
		return b''
	
	# Your Mission for Weapons Role #

	### How could you disable JUST the shields? JUST the load button? JUST the fire button? ###

	### How could you switch the interaction of the tubes (loading/firing 2 loads/fires 1 and vice-versa) ###

	### Can you trick the console into only loading Mine, regardless of what ordinance is selected? ###

	### How could you fire both tubes immediately once a target has been picked? ###

	# Your Mission for Helm Role #

	### How could you disable the reverse button? ###

	### How could you set the warp factor (bottom-left vertical green bar) so that it only goes between 0 and 4? ###

	### How could you set the impulse (bottom-left vertical yellow bar) so that it rounds to the nearest increment of 10? ###

	### How could you force the ship to only turn left? ###

	# What can you do for other roles? #
	
	now = datetime.datetime.now()
	print(f'{now}: client --> {bytes_to_string(client_packet)}', end='\n') #change \n to \r if you just want to see the most recent packet
	
	return client_packet
